/**
 * MAC-prefix (OUI) → vendor lookup + best-effort device-type classification.
 *
 * Vendor names come from a merged registry (src/lib/oui/oui-registry.json, 24-bit;
 * + oui-registry-fine.json for 28/36-bit MA-M/MA-S), regenerated by
 * `npm run oui:refresh` from IEEE MA-L/MA-M/MA-S + Wireshark manuf + Nmap prefixes.
 * Device type is inferred from SNMP sysDescr > DHCP vendor-class > hostname keywords
 * > vendor-name keywords > randomized-MAC detection.
 *
 * SERVER/CLI ONLY: importing this pulls the ~1MB registry. UI components should
 * import the lightweight vocabulary from ./types instead. Re-exported here for
 * server-side convenience.
 */
import REGISTRY from "./oui-registry.json";
import FINE from "./oui-registry-fine.json";
import DHCP_FP_JSON from "./dhcp-fingerprints.json";
import { DEVICE_TYPE_LABELS, type DeviceType } from "./types";

export { DEVICE_TYPE_LABELS, type DeviceType };

const OUI: Record<string, string> = REGISTRY as Record<string, string>;
// Finer-grained MA-M (28-bit / 7 hex) and MA-S (36-bit / 9 hex) assignments, where
// multiple vendors share one 24-bit block. Checked longest-first so the specific
// MA-S/MA-M owner wins over the 24-bit block holder. Empty until `npm run oui:refresh`
// populates it (IEEE MA-M/MA-S + Wireshark /28 /36 entries).
const OUI_FINE: Record<string, string> = FINE as Record<string, string>;
// DHCP option-55 (parameter request list) fingerprint → device type. A small,
// HAND-CURATED seed (src/lib/oui/dhcp-fingerprints.json) of high-confidence,
// common fingerprints — keyed by the decimal option codes joined with commas
// (order-sensitive — it IS the fingerprint). The open ODbL source is a frozen
// 2014 snapshot not worth auto-pulling; the AI adjudicator covers everything this
// seed misses, so keep the seed conservative rather than broad-but-wrong.
const DHCP_FP: Record<string, string> = DHCP_FP_JSON as Record<string, string>;
const HEX6 = /^[0-9A-F]{6}$/;

/** Strip separators, uppercase, return the first 6 hex chars (the OUI), or null. */
export function macPrefix(mac: string | null | undefined): string | null {
  if (!mac) return null;
  const clean = mac.replace(/[^0-9a-fA-F]/g, "").toUpperCase();
  if (clean.length < 6) return null;
  const p = clean.slice(0, 6);
  return HEX6.test(p) ? p : null;
}

/** True if the MAC is locally administered (2nd-least-significant bit of byte 0). */
export function isLocallyAdministered(mac: string | null | undefined): boolean {
  const p = macPrefix(mac);
  if (!p) return false;
  const firstByte = parseInt(p.slice(0, 2), 16);
  return (firstByte & 0x02) === 0x02;
}

/**
 * OUI → manufacturer, longest-prefix first: MA-S (36-bit) → MA-M (28-bit) →
 * MA-L (24-bit). With an empty fine map this is exactly the old 24-bit behaviour.
 */
export function lookupVendor(mac: string | null | undefined): string | null {
  if (!mac) return null;
  const clean = mac.replace(/[^0-9a-fA-F]/g, "").toUpperCase();
  if (clean.length >= 9) {
    const v = OUI_FINE[clean.slice(0, 9)];
    if (v) return v;
  }
  if (clean.length >= 7) {
    const v = OUI_FINE[clean.slice(0, 7)];
    if (v) return v;
  }
  const p = clean.slice(0, 6);
  return HEX6.test(p) ? (OUI[p] ?? null) : null;
}

/** Treat empty / "unknown" / "n/a" vendor strings as "no vendor". */
export function isBlankVendor(v: string | null | undefined): boolean {
  if (!v) return true;
  const s = v.trim().toLowerCase();
  return (
    s === "" || s === "unknown" || s === "n/a" || s === "-" || s === "none" || s === "?"
  );
}

// ---- classification rules (most-specific signal wins) ----------------------

const HOSTNAME_RULES: { type: DeviceType; re: RegExp }[] = [
  { type: "printer", re: /print|laserjet|officejet|\bmfp\b|\bmfc\b|copier|kyocera|lexmark|ricoh|xerox|brother|canon|epson/i },
  { type: "phone", re: /\bvoip\b|\bsip\b|\bphone\b|polycom|yealink|grandstream|\bspa\d/i },
  { type: "camera", re: /\bcam\b|camera|axis|hikvision|dahua|avigilon|\bnvr\b|\bdvr\b/i },
  { type: "display", re: /promethean|activpanel|smart ?board|clevertouch|viewboard|interactive ?panel|interactive ?display|\bIFP\b/i },
  { type: "media", re: /chromecast|apple-?tv|\broku\b|fire-?tv|\bsonos\b|smart-?tv|\bvizio\b/i },
  { type: "ap", re: /\bap[-_ ]?\d|access[-_ ]?point|\bwap\b|aironet|meraki|aruba|unifi|\bwifi\b/i },
  { type: "switch", re: /\bsw[-_ ]?\d|switch|catalyst|\bcsw\b|\bdsw\b|\basw\b/i },
  { type: "router", re: /\brtr\b|router|gateway|\bgw[-_ ]?\d/i },
  { type: "firewall", re: /firewall|\bfw[-_ ]?\d|fortigate|palo|sonicwall|\basa\b/i },
  { type: "server", re: /\bsrv\b|server|\besxi\b|\bvcenter\b|\bdc0?\d\b|\bsql\b|\bdns\b|\bdhcp\b/i },
  { type: "storage", re: /\bnas\b|synology|qnap|\bsan\b|isilon|netapp/i },
  { type: "computer", re: /\bpc[-_ ]?\d|desktop|laptop|workstation|\bwks\b|chromebook|macbook|imac/i },
  { type: "mobile", re: /iphone|ipad|android|galaxy|pixel|mobile|tablet/i },
];

const SNMP_RULES: { type: DeviceType; re: RegExp }[] = [
  { type: "switch", re: /catalyst|switch|\bIOS\b|procurve|aruba.*switch|\bEXOS\b|nx-?os/i },
  { type: "router", re: /router|\bISR\b|\bASR\b|mikrotik|\bRouterOS\b/i },
  { type: "firewall", re: /fortigate|palo alto|\bASA\b|sonicwall|firewall/i },
  { type: "ap", re: /access point|\bAP\b|aironet|wireless/i },
  { type: "printer", re: /jetdirect|laserjet|officejet|printer|fiery|kyocera|lexmark/i },
  { type: "camera", re: /camera|\bIP cam|axis|hikvision/i },
  { type: "server", re: /windows server|linux|ubuntu|\besxi\b|vmware|red hat|centos/i },
];

// Vendor-name rules only for categories a manufacturer reliably implies. Network
// vendors (Cisco/HPE/Juniper) are intentionally omitted — vendor alone can't tell
// a switch from a router from a phone; those defer to hostname/SNMP.
//
// `strong` marks single-purpose vendors whose product line reliably IS the role
// (a Hikvision device is a camera) — the scored layer trusts these enough to
// settle them. `strong:false` marks multi-product vendors (Aruba/Ubiquiti/Ruckus
// also make switches & cameras), so an `ap` guess there stays low-confidence.
const VENDOR_RULES: { type: DeviceType; re: RegExp; strong: boolean }[] = [
  { type: "camera", strong: true, re: /\baxis\b|hikvision|dahua|hanwha|vivotek|bosch security|mobotix|geovision|uniview|amcrest|reolink|wyze|lorex|swann/i },
  { type: "phone", strong: true, re: /polycom|\bpoly\b|yealink|grandstream|\bmitel\b|aastra|\bsnom\b|sangoma|fanvil|audiocodes|cyberdata/i },
  { type: "printer", strong: true, re: /lexmark|kyocera|\bricoh\b|\bxerox\b|brother|\bcanon\b|\bepson\b|zebra|konica|\bsharp\b|toshiba tec|primera|\bdymo\b|\bsato\b|oki data|pantum|\bsindoh\b/i },
  { type: "storage", strong: true, re: /synology|\bqnap\b|netapp|\bdrobo\b|western digital|\bseagate\b|buffalo|terramaster/i },
  { type: "firewall", strong: true, re: /fortinet|palo alto|sonicwall|watchguard|\bsophos\b|check point|barracuda|\bzyxel\b.*(firewall|security)/i },
  { type: "vm", strong: true, re: /vmware|\bqemu\b|virtualbox|\bxen\b|parallels|nutanix/i },
  // Education interactive displays / boards — these makers are single-purpose.
  // ViewSonic/BenQ are deliberately omitted here (broad monitor lines); their
  // boards are caught by the ViewBoard/IFP hostname rule instead.
  { type: "display", strong: true, re: /promethean|smarttech|smart ?technolog|clevertouch|newline interactive|boxlight|\bmimio\b|avocor/i },
  // Streaming / media players. Roku & Sonos are single-purpose; smart-TV brands
  // (Samsung/LG/Vizio) are NOT here — they're ambiguous and rely on the mDNS hint.
  { type: "media", strong: true, re: /\broku\b|\bsonos\b/i },
  { type: "ap", strong: false, re: /\baruba\b|ubiquiti|ruckus|aerohive|\bmist\b|cambium|edgecore|\bxirrus\b|open ?mesh/i },
];

// DHCP option-60 (vendor class id) → device type. This is a strong passive
// signal for endpoints that never speak SNMP — the classic device fingerprint.
const DHCP_VENDOR_RULES: { type: DeviceType; re: RegExp }[] = [
  { type: "printer", re: /jetdirect|hp.*(jet|print)|hewlett.*print|lexmark|\bcanon\b|epson|brother|kyocera|\bricoh\b|\bxerox\b|\bzebra\b|sharp.*mfp|toshiba.*tec/i },
  { type: "ap", re: /\baruba\b|arubaap|cisco ap|\bAIR-|meraki|\bmist\b|ruckus|ubiquiti|\bUAP\b|aerohive|cambium|engenius/i },
  { type: "phone", re: /polycom|yealink|grandstream|cisco ip phone|\bSEP[0-9A-F]|\bsnom\b|\bmitel\b|avaya.*phone|sip|fanvil|audiocodes/i },
  { type: "camera", re: /\baxis\b|hikvision|\bdahua\b|\bACTi\b|avigilon|hanwha|vivotek/i },
  { type: "firewall", re: /sonicwall|fortigate|palo ?alto|watchguard|\bsophos\b/i },
  { type: "storage", re: /synology|\bqnap\b|netapp|\bdrobo\b/i },
  { type: "vm", re: /\bvmware\b|\bqemu\b|virtualbox/i },
  { type: "mobile", re: /android-dhcp|\biphone\b|\bipad\b|\bipod\b|dhcpcd-.*android|samsung-android|\bMobile\b/i },
  { type: "computer", re: /MSFT|microsoft|windows|\bMacBook\b|chromeos|cros\b/i },
];

/** DHCP option-60 vendor-class id → device type (the classic vendor fingerprint). */
export function classifyByDhcpVendor(vendorClass: string | null | undefined): DeviceType | null {
  if (!vendorClass) return null;
  for (const r of DHCP_VENDOR_RULES) if (r.re.test(vendorClass)) return r.type;
  return null;
}

/**
 * DHCP option-55 (parameter request list) fingerprint → device type. Normalizes
 * the incoming list to decimal option codes joined by commas, then looks it up in
 * the curated DHCP_FP seed. Returns null on no match (the AI adjudicator handles
 * the long tail this small seed doesn't cover).
 */
export function classifyByDhcpFingerprint(paramList: string | null | undefined): DeviceType | null {
  if (!paramList) return null;
  const key = (paramList.match(/\d+/g) ?? []).join(",");
  if (!key) return null;
  return (DHCP_FP[key] as DeviceType) ?? null;
}

/** Combined DHCP classification: option-60 vendor class first, then option-55. */
export function classifyByDhcp(
  vendorClass: string | null | undefined,
  paramList?: string | null,
): DeviceType | null {
  return classifyByDhcpVendor(vendorClass) ?? classifyByDhcpFingerprint(paramList);
}

// Per-signal matchers, exposed so the scored-fusion layer (src/lib/classify) can
// gather one Candidate per signal instead of only the single winner. Each reuses
// the rule tables above and returns the matched type or null.

/** SNMP sysDescr / LLDP system-description keyword → type. */
export function classifyBySnmpDescr(s: string | null | undefined): DeviceType | null {
  if (!s) return null;
  for (const r of SNMP_RULES) if (r.re.test(s)) return r.type;
  return null;
}

/** Hostname keyword → type. */
export function classifyByHostname(s: string | null | undefined): DeviceType | null {
  if (!s) return null;
  for (const r of HOSTNAME_RULES) if (r.re.test(s)) return r.type;
  return null;
}

/** Vendor-name keyword → type (only categories a manufacturer reliably implies). */
export function classifyByVendorName(v: string | null | undefined): DeviceType | null {
  return classifyByVendorRole(v)?.type ?? null;
}

/**
 * Vendor-name → {type, strong}. `strong` is true for single-purpose vendors whose
 * product line reliably IS the role; the scored layer (src/lib/classify) uses it to
 * decide whether a vendor-only match is trustworthy enough to settle. Returns null
 * when no curated rule matches.
 */
export function classifyByVendorRole(
  v: string | null | undefined,
): { type: DeviceType; strong: boolean } | null {
  if (!v || isBlankVendor(v)) return null;
  for (const r of VENDOR_RULES) if (r.re.test(v)) return { type: r.type, strong: r.strong };
  return null;
}

// mDNS (Bonjour) / SSDP (UPnP) coarse device_hint → type. The collector
// (collector/discovery/mdns_ssdp.py:_HINTS) attaches this hint to chatty
// service-advertising endpoints that OUI/ARP can't identify — the single strongest
// signal for Apple TVs, Chromecasts, AirPrint printers, Sonos, Rokus, cameras.
const SERVICE_HINT_MAP: Record<string, DeviceType> = {
  printer: "printer",
  camera: "camera",
  chromecast: "media",
  "cast-device": "media",
  roku: "media",
  sonos: "media",
  "media-player": "media",
  "apple-av": "media",
  "media-server": "storage",
  computer: "computer",
  "apple-host": "computer",
  gateway: "router",
  // web-ui / apple-network are too generic to assign a type.
};

// Fallback: raw mDNS service-type substring → type, when no coarse hint is set.
const SERVICE_TYPE_RULES: { type: DeviceType; re: RegExp }[] = [
  { type: "printer", re: /_ipp\b|_ipps\b|_printer\b|_pdl-datastream/i },
  { type: "media", re: /_googlecast|_airplay|_raop|_sonos|_spotify-connect/i },
  { type: "camera", re: /_axis-video|_rtsp\b/i },
  { type: "computer", re: /_workstation|_smb\b|_afpovertcp/i },
];

/** mDNS/SSDP service hint (+ raw service types) → device type. */
export function classifyByServiceHint(
  hint: string | null | undefined,
  services?: string[] | null,
): DeviceType | null {
  if (hint) {
    const t = SERVICE_HINT_MAP[hint.trim().toLowerCase()];
    if (t) return t;
  }
  if (services && services.length) {
    const joined = services.join(" ");
    for (const r of SERVICE_TYPE_RULES) if (r.re.test(joined)) return r.type;
  }
  return null;
}

/**
 * Best-effort device classification. Priority: SNMP sysDescr > DHCP vendor-class
 * fingerprint > hostname keywords > OUI vendor-name keywords > randomized-MAC
 * heuristic > unknown.
 */
export function classifyDeviceType(input: {
  mac?: string | null;
  vendor?: string | null;
  hostname?: string | null;
  snmpSysDescr?: string | null;
  dhcpVendorClass?: string | null;
  dhcpParamList?: string | null;
}): DeviceType {
  const { mac, hostname, snmpSysDescr } = input;
  const vendor = input.vendor ?? lookupVendor(mac);

  if (snmpSysDescr) for (const r of SNMP_RULES) if (r.re.test(snmpSysDescr)) return r.type;
  const byDhcp = classifyByDhcp(input.dhcpVendorClass, input.dhcpParamList);
  if (byDhcp) return byDhcp;
  if (hostname) for (const r of HOSTNAME_RULES) if (r.re.test(hostname)) return r.type;
  if (vendor && !isBlankVendor(vendor))
    for (const r of VENDOR_RULES) if (r.re.test(vendor)) return r.type;

  // Randomized/private MAC with no registry match: a deliberately-randomized
  // address (MAC privacy). Label it as such rather than guessing a device.
  if (isLocallyAdministered(mac) && !lookupVendor(mac)) return "randomized";

  return "unknown";
}

const RANDOMIZED_VENDOR = "Randomized (private) MAC";

/** One-shot enrichment for a host row: fill vendor from OUI, classify type. */
export function enrichHost(input: {
  mac?: string | null;
  vendor?: string | null;
  hostname?: string | null;
  snmpSysDescr?: string | null;
  dhcpVendorClass?: string | null;
  dhcpParamList?: string | null;
}): { vendor: string | null; deviceType: DeviceType } {
  let vendor = isBlankVendor(input.vendor) ? lookupVendor(input.mac) : (input.vendor ?? null);
  const deviceType = classifyDeviceType({ ...input, vendor });
  if (!vendor && deviceType === "randomized") vendor = RANDOMIZED_VENDOR;
  return { vendor: vendor ?? null, deviceType };
}
